### ISSUE TITLE
Target link does not work if link has title

### ISSUE THREAD

**Issue by exeqdev** [hokkaidoperson/DokuWiki-TargetLink-Plugin#2]
syntax.php:27

`$this->Lexer->addSpecialPattern('\[\[target=.*\|.*?\]\](?!\])',$mode,'plugin_targetlink');`

Regxp match links with target and link but matches incorrectly link expression when have title

regexp _/\[\[(target.*)\|(.*?)\]\](?!\])/_ tested with **[[target=_self|namespace:page#here|title]]**

group1=>target=_self|namespace:page#here
group2=>title
SAMPLE: https://regex101.com/r/w0OIkj

when it should be
group1=>target=_self
group2=>namespace:page#here|title
SAMPLE: https://regex101.com/r/w0OIkj/2

solution:
change syntax.php:27 with:
`$this->Lexer->addSpecialPattern('\[\[target=[^\|]*\|.*?\]\](?!\])',$mode,'plugin_targetlink');`

already requeste pull with changes [https://github.com/hokkaidoperson/DokuWiki-TargetLink-Plugin/pull/1](https://github.com/hokkaidoperson/DokuWiki-TargetLink-Plugin/pull/1)
`https://github.com/hokkaidoperson/DokuWiki-TargetLink-Plugin/pull/1`

**Comment by hokkaidoperson** [comment]
I'm sorry that I got late to merge your request...
I did it now.
